services:
  bot:
    build:
      context: https://github.com/albertopasqualetto/amazon-deals-telegram-bot.git#docker
      dockerfile: Dockerfile
    container_name: amazon-deals-telegram-bot
    env_file:
      - .env
    environment:
      - REMOTE_CHROMIUM = "http://selenium:4444/wd/hub"
    depends_on:
      - selenium
    restart: always

  selenium:
    image: selenium/standalone-chromium:latest
    container_name: adtb-selenium
    shm_size: 2g
    healthcheck:
     test: ["CMD", "curl", "-I", "http://selenium:4444/wd/hub/status"]
     interval: 1m
     timeout: 60s
     retries: 3
     start_period: 300s
    restart: always